# Project identification
sonar.projectKey=pfe-frontend
sonar.organization=rimtrack-admin

# The script will override these if passed via command line, 
# but we define them here for local scanner compatibility.
sonar.projectName=PFE Frontend
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts

# Path to test results and coverage
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/web_admin/lcov.info

# Source encoding
sonar.sourceEncoding=UTF-8
